import { useId, useMemo, useRef, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import Svg, { Circle, Defs, LinearGradient, Stop } from 'react-native-svg';
import { colors, fontSizes, fontWeights, spacing } from '../tokens';

const clamp = (value: number, min: number, max: number) => Math.min(Math.max(value, min), max);
export function ProgressBar({ value = 0, max = 100, label, valueLabel, color = colors.accent, height = 8 }: { value?: number; max?: number; label?: React.ReactNode; valueLabel?: React.ReactNode; color?: string; height?: number }) {
  const safeMax = max > 0 ? max : 1; const percent = clamp(value / safeMax, 0, 1);
  return <View accessible accessibilityRole="progressbar" accessibilityValue={{ min: 0, max: safeMax, now: clamp(value, 0, safeMax) }}><View style={styles.meterLabels}>{label ? <Text style={styles.label}>{label}</Text> : <View />}{valueLabel ? <Text style={styles.value}>{valueLabel}</Text> : null}</View><View style={[styles.track, { height, borderRadius: height / 2 }]}><View style={{ width: `${percent * 100}%`, height, borderRadius: height / 2, backgroundColor: color }} /></View></View>;
}
export function ProgressRing({ current = 0, target = 100, label, size = 104, strokeWidth = 8, colorStart = colors.data.cool, colorEnd = colors.accent, showTarget = true }: { current?: number; target?: number; label?: React.ReactNode; size?: number; strokeWidth?: number; colorStart?: string; colorEnd?: string; showTarget?: boolean }) {
  const gradientId = `progress-${useId().replace(/:/g, '')}`;
  const safeTarget = target > 0 ? target : 1; const ratio = clamp(current / safeTarget, 0, 1); const radius = (size - strokeWidth) / 2; const circumference = 2 * Math.PI * radius;
  return <View accessible accessibilityRole="progressbar" accessibilityLabel={typeof label === 'string' ? label : 'Progress'} accessibilityValue={{ min: 0, max: safeTarget, now: clamp(current, 0, safeTarget) }} style={{ width: size, height: size, alignItems: 'center', justifyContent: 'center' }}><Svg width={size} height={size} style={StyleSheet.absoluteFill}><Defs><LinearGradient id={gradientId} x1="0" y1="0" x2="1" y2="1"><Stop offset="0" stopColor={colorStart} /><Stop offset="1" stopColor={colorEnd} /></LinearGradient></Defs><Circle cx={size / 2} cy={size / 2} r={radius} stroke={colors.data.track} strokeWidth={strokeWidth} fill="none" /><Circle cx={size / 2} cy={size / 2} r={radius} stroke={`url(#${gradientId})`} strokeWidth={strokeWidth} fill="none" strokeLinecap="round" strokeDasharray={`${circumference} ${circumference}`} strokeDashoffset={circumference * (1 - ratio)} rotation="-90" origin={`${size / 2}, ${size / 2}`} /></Svg><Text style={styles.ringValue}>{current}</Text>{showTarget ? <Text style={styles.ringTarget}>/ {target}</Text> : null}{label ? <Text style={styles.ringLabel}>{label}</Text> : null}</View>;
}
export type HeatmapMonth = { label: string; weekIndex: number };
export function Heatmap({ values, months = [], year, totalWorkouts, workoutDays, caption, dotSize = 8, gap = 3, scrollable, fluid = false, todayIndex, selectedIndex, onSelectDay, showLegend = true }: { values: (number | null)[]; months?: HeatmapMonth[]; year: number | string; totalWorkouts: number; workoutDays: number; caption?: string; dotSize?: number; gap?: number; scrollable?: boolean; fluid?: boolean; todayIndex?: number; selectedIndex?: number | null; onSelectDay?: (index: number) => void; showLegend?: boolean }) {
  const weekCount = Math.ceil(values.length / 7) || 1;
  const scroller = useRef<ScrollView>(null);
  const [measuredWidth, setMeasuredWidth] = useState(0);
  const dot = fluid && measuredWidth ? Math.max(3, Math.min(dotSize, Math.floor((measuredWidth - 22 - weekCount * gap) / weekCount))) : dotSize;
  const step = dot + gap;
  const weeks = useMemo(() => Array.from({ length: weekCount }, (_, week) => values.slice(week * 7, week * 7 + 7)), [values, weekCount]);
  const grid = <View accessibilityLabel={`${year} activity: ${totalWorkouts} workouts across ${workoutDays} days`} style={styles.heatGrid}>{weeks.map((week, weekIndex) => <View key={weekIndex} style={{ width: dot, marginRight: gap }}>{week.map((count, dayIndex) => {
    const index = weekIndex * 7 + dayIndex;
    const cell = <View style={{ width: dot, height: dot, marginBottom: gap, borderRadius: dot / 2, backgroundColor: count === null ? 'transparent' : count > 0 ? colors.data.heatOn : colors.data.heatEmpty, borderWidth: index === selectedIndex || index === todayIndex ? 1 : 0, borderColor: index === selectedIndex ? colors.text.primary : colors.accent }} />;
    return onSelectDay && count !== null ? <Pressable key={index} accessibilityRole="button" accessibilityLabel={`Day ${index + 1}: ${count} workouts`} hitSlop={2} onPress={() => onSelectDay(index)}>{cell}</Pressable> : <View key={index}>{cell}</View>;
  })}</View>)}</View>;
  const content = fluid ? grid : <ScrollView ref={scroller} horizontal showsHorizontalScrollIndicator={false} onContentSizeChange={() => scroller.current?.scrollToEnd({ animated: false })}>{grid}</ScrollView>;
  return <View onLayout={fluid ? (event) => setMeasuredWidth(event.nativeEvent.layout.width) : undefined}><View style={styles.heatHead}><Text style={styles.heatTitle}>{`${year} Workout Activity`}</Text><Text style={styles.heatCaption}>{caption ?? `${totalWorkouts} workouts in ${workoutDays} days`}</Text></View><View style={styles.heatBody}><View style={[styles.dayLabels, { paddingTop: 14 }]}>{['S', 'M', 'T', 'W', 'T', 'F', 'S'].map((day, index) => <View key={`${day}-${index}`} style={{ height: dot, marginBottom: gap, justifyContent: 'center' }}><Text style={styles.axis}>{day}</Text></View>)}</View><View style={styles.heatContent}><View style={styles.monthRow}>{months.map((month) => <Text key={`${month.label}-${month.weekIndex}`} style={[styles.axis, styles.monthPosition, { left: month.weekIndex * step }]}>{month.label}</Text>)}</View>{scrollable === false && !fluid ? grid : content}</View></View>{showLegend ? <View style={styles.heatLegend}><Text style={styles.axis}>Less</Text><View style={styles.legendDots}><View style={[styles.legendDot, { backgroundColor: colors.data.heatEmpty }]} /><View style={[styles.legendDot, { backgroundColor: colors.accent }]} /></View><Text style={styles.axis}>More</Text></View> : null}</View>;
}
const styles = StyleSheet.create({ meterLabels: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing[2] }, label: { color: colors.text.muted, fontFamily: fontWeights.medium, fontSize: fontSizes.base }, value: { color: colors.text.primary, fontFamily: fontWeights.monoMedium, fontSize: fontSizes.sm }, track: { overflow: 'hidden', backgroundColor: colors.data.track }, ringValue: { color: colors.text.primary, fontFamily: fontWeights.monoBold, fontSize: fontSizes.xxl }, ringTarget: { color: colors.text.secondary, fontFamily: fontWeights.mono, fontSize: fontSizes.xs }, ringLabel: { color: colors.text.muted, fontFamily: fontWeights.medium, fontSize: fontSizes.xs, marginTop: 2 }, heatHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: spacing[4], marginBottom: spacing[5] }, heatTitle: { color: colors.accent, fontFamily: fontWeights.medium, fontSize: fontSizes.lg }, heatCaption: { color: colors.text.secondary, fontFamily: fontWeights.regular, fontSize: fontSizes.sm, textAlign: 'right' }, heatBody: { flexDirection: 'row' }, dayLabels: { marginRight: 6 }, heatContent: { flex: 1, minWidth: 0 }, monthRow: { height: 14 }, monthPosition: { position: 'absolute', bottom: 2 }, axis: { color: colors.text.secondary, fontFamily: fontWeights.regular, fontSize: fontSizes.xs }, heatGrid: { flexDirection: 'row' }, heatLegend: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing[4] }, legendDots: { flexDirection: 'row', gap: spacing[1], alignItems: 'center' }, legendDot: { width: 10, height: 10, borderRadius: 5 } });
