import { useId } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import Svg, { Circle, Defs, LinearGradient, Stop } from 'react-native-svg';
import { colors, fontSizes, fontWeights, spacing } from '../tokens';

const clamp = (value: number, min: number, max: number) => Math.min(Math.max(value, min), max);
export function ProgressBar({ value = 0, max = 100, label, valueLabel, color = colors.accent, height = 8 }: { value?: number; max?: number; label?: React.ReactNode; valueLabel?: React.ReactNode; color?: string; height?: number }) {
  const safeMax = max > 0 ? max : 1; const percent = clamp(value / safeMax, 0, 1);
  return <View accessible accessibilityRole="progressbar" accessibilityValue={{ min: 0, max: safeMax, now: clamp(value, 0, safeMax) }}><View style={styles.meterLabels}>{label ? <Text style={styles.label}>{label}</Text> : <View />}{valueLabel ? <Text style={styles.value}>{valueLabel}</Text> : null}</View><View style={[styles.track, { height, borderRadius: height / 2 }]}><View style={{ width: `${percent * 100}%`, height, borderRadius: height / 2, backgroundColor: color }} /></View></View>;
}
export function ProgressRing({ current = 0, target = 100, label, size = 104, strokeWidth = 8, colorStart = colors.data.cool, colorEnd = colors.accent, showTarget = true }: { current?: number; target?: number; label?: React.ReactNode; size?: number; strokeWidth?: number; colorStart?: string; colorEnd?: string; showTarget?: boolean }) {
  const gradientId = `progress-${useId().replace(/:/g, '')}`;
  const safeTarget = target > 0 ? target : 1; const ratio = clamp(current / safeTarget, 0, 1); const radius = (size - strokeWidth) / 2; const circumference = 2 * Math.PI * radius;
  return <View accessible accessibilityRole="progressbar" accessibilityLabel={typeof label === 'string' ? label : 'Progress'} accessibilityValue={{ min: 0, max: safeTarget, now: clamp(current, 0, safeTarget) }} style={{ width: size, height: size, alignItems: 'center', justifyContent: 'center' }}><Svg width={size} height={size} style={StyleSheet.absoluteFill}><Defs><LinearGradient id={gradientId} x1="0" y1="0" x2="1" y2="1"><Stop offset="0" stopColor={colorStart} /><Stop offset="1" stopColor={colorEnd} /></LinearGradient></Defs><Circle cx={size / 2} cy={size / 2} r={radius} stroke={colors.data.track} strokeWidth={strokeWidth} fill="none" /><Circle cx={size / 2} cy={size / 2} r={radius} stroke={`url(#${gradientId})`} strokeWidth={strokeWidth} fill="none" strokeLinecap="round" strokeDasharray={`${circumference} ${circumference}`} strokeDashoffset={circumference * (1 - ratio)} rotation="-90" origin={`${size / 2}, ${size / 2}`} /></Svg><Text style={styles.ringValue}>{current}</Text>{showTarget ? <Text style={styles.ringTarget}>/ {target}</Text> : null}{label ? <Text style={styles.ringLabel}>{label}</Text> : null}</View>;
}
export type HeatmapMonth = { label: string; weekIndex: number };
export function Heatmap({ values, months = [], year, totalWorkouts, workoutDays, caption, dotSize = 8, gap = 3, scrollable, todayIndex, selectedIndex, onSelectDay, showLegend = true }: { values: (number | null)[]; months?: HeatmapMonth[]; year: number | string; totalWorkouts: number; workoutDays: number; caption?: string; dotSize?: number; gap?: number; scrollable?: boolean; todayIndex?: number; selectedIndex?: number | null; onSelectDay?: (index: number) => void; showLegend?: boolean }) {
  const weeks = Math.ceil(values.length / 7); const grid = <View accessibilityLabel={`${year} activity: ${totalWorkouts} workouts across ${workoutDays} days`} style={[styles.heatGrid, { width: weeks * (dotSize + gap) }]}>{values.map((count, index) => count === null ? <View key={index} style={{ width: dotSize, height: dotSize, margin: gap / 2 }} /> : <Pressable key={index} accessibilityRole={onSelectDay ? 'button' : undefined} disabled={!onSelectDay} onPress={onSelectDay ? () => onSelectDay(index) : undefined} accessibilityLabel={`Day ${index + 1}: ${count} workouts`} style={{ width: dotSize, height: dotSize, margin: gap / 2, borderRadius: dotSize / 3, backgroundColor: count > 0 ? colors.data.heatOn : colors.data.heatEmpty, borderWidth: index === selectedIndex || index === todayIndex ? 1.5 : 0, borderColor: index === selectedIndex ? colors.text.primary : colors.accent }} />)}</View>;
  return <View><View style={styles.meterLabels}><Text style={styles.heading}>{year}</Text><Text style={styles.value}>{caption ?? `${totalWorkouts} workouts · ${workoutDays} days`}</Text></View>{months.length ? <View style={styles.months}>{months.map((month) => <Text key={`${month.label}-${month.weekIndex}`} style={styles.month}>{month.label}</Text>)}</View> : null}{scrollable ? <ScrollView horizontal showsHorizontalScrollIndicator={false}>{grid}</ScrollView> : grid}{showLegend ? <Text style={styles.legend}>Rest day · Workout day</Text> : null}</View>;
}
const styles = StyleSheet.create({ meterLabels: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing[2] }, label: { color: colors.text.muted, fontFamily: fontWeights.medium, fontSize: fontSizes.base }, value: { color: colors.text.primary, fontFamily: fontWeights.monoMedium, fontSize: fontSizes.sm }, track: { overflow: 'hidden', backgroundColor: colors.data.track }, ringValue: { color: colors.text.primary, fontFamily: fontWeights.monoBold, fontSize: fontSizes.xxl }, ringTarget: { color: colors.text.secondary, fontFamily: fontWeights.mono, fontSize: fontSizes.xs }, ringLabel: { color: colors.text.muted, fontFamily: fontWeights.medium, fontSize: fontSizes.xs, marginTop: 2 }, heatGrid: { flexDirection: 'column', flexWrap: 'wrap', height: 7 * 14, alignContent: 'flex-start' }, heading: { color: colors.text.primary, fontFamily: fontWeights.bold, fontSize: fontSizes.xl }, months: { flexDirection: 'row', justifyContent: 'space-between' }, month: { color: colors.text.secondary, fontFamily: fontWeights.medium, fontSize: fontSizes.xs }, legend: { color: colors.text.secondary, fontFamily: fontWeights.regular, fontSize: fontSizes.xs, marginTop: spacing[2] } });
