import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Icon } from '../icon/Icon';
import { colors, effects, fontSizes, fontWeights, radii, spacing } from '../tokens';
import { Card, IconButton } from './core';

type Tone = 'success' | 'error' | 'warning' | 'info';
const toneMap = { success: { ink: colors.accent, wash: colors.accentWashStrong, icon: 'check' }, error: { ink: colors.status.errorInk, wash: colors.status.errorWash, icon: 'alert-triangle' }, warning: { ink: colors.status.warningInk, wash: colors.status.warningWash, icon: 'alert-triangle' }, info: { ink: colors.status.info, wash: colors.status.infoWash, icon: 'info' } } as const;
export function Alert({ tone = 'info', children, onClose, toast }: { tone?: Tone; children: React.ReactNode; onClose?: () => void; toast?: boolean }) { const palette = toneMap[tone]; return <View accessibilityRole="alert" accessibilityLiveRegion="polite" style={[styles.alert, { backgroundColor: palette.wash }, toast && styles.toast]}><Icon name={palette.icon} color={palette.ink} /><Text style={[styles.alertText, { color: palette.ink }]}>{children}</Text>{onClose ? <IconButton icon="x" label="Close alert" onPress={onClose} /> : null}</View>; }

export function Dialog({ open = false, title, subtitle, footer, onClose, width = 800, children }: { open?: boolean; title: React.ReactNode; subtitle?: React.ReactNode; footer?: React.ReactNode; onClose?: () => void; width?: number; children?: React.ReactNode }) { return <Modal visible={open} transparent animationType="fade" onRequestClose={onClose}><SafeAreaView style={styles.scrim}><View accessibilityViewIsModal accessibilityRole="summary" style={[styles.dialog, effects.shadow.dialog, { maxWidth: width }]}><View style={styles.header}><View style={styles.grow}><Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>{onClose ? <IconButton icon="x" label="Close dialog" onPress={onClose} /> : null}</View><ScrollView>{children}</ScrollView>{footer ? <View style={styles.footer}>{footer}</View> : null}</View></SafeAreaView></Modal>; }

export function Sheet({ open = true, title, onClose, maxHeight = '88%', showHandle = true, scrimClose = true, footer, children }: { open?: boolean; title?: React.ReactNode; onClose?: () => void; maxHeight?: number | `${number}%`; showHandle?: boolean; scrimClose?: boolean; footer?: React.ReactNode; children?: React.ReactNode }) { return <Modal visible={open} transparent animationType="slide" onRequestClose={onClose}><View style={styles.sheetScrim}><Pressable accessibilityLabel={scrimClose ? 'Close sheet' : undefined} disabled={!scrimClose} onPress={scrimClose ? onClose : undefined} style={StyleSheet.absoluteFill} /><SafeAreaView edges={['bottom']} style={[styles.sheet, { maxHeight }]}>{showHandle ? <View style={styles.handle} /> : null}{title ? <View style={styles.header}><Text style={styles.title}>{title}</Text>{onClose ? <IconButton icon="x" label="Close sheet" onPress={onClose} /> : null}</View> : null}<ScrollView>{children}</ScrollView>{footer ? <View style={styles.footer}>{footer}</View> : null}</SafeAreaView></View></Modal>; }

export function EmptyState({ icon = 'dumbbell', title, body, action, secondary, tone = 'quiet' }: { icon?: string; title: React.ReactNode; body?: React.ReactNode; action?: React.ReactNode; secondary?: React.ReactNode; tone?: 'accent' | 'quiet' }) { return <Card tone={tone === 'accent' ? 'accent' : 'quiet'} style={styles.empty}><View style={styles.hex}><View style={styles.hexIcon}><Icon name={icon} color={colors.accent} size={28} /></View></View><Text style={styles.title}>{title}</Text>{body ? <Text style={styles.emptyBody}>{body}</Text> : null}{action}<View>{secondary}</View></Card>; }
export function Skeleton({ variant = 'rect', width = '100%', height = variant === 'text' ? 14 : 80, radius }: { variant?: 'rect' | 'text' | 'circle'; width?: number | `${number}%`; height?: number | `${number}%`; radius?: number }) { const circle = variant === 'circle'; return <View accessibilityLabel="Loading content" style={{ width, height, borderRadius: radius ?? (circle ? 999 : variant === 'text' ? 4 : radii.sm), backgroundColor: colors.surface.active }} />; }
export function Spinner({ size = 15, tone = 'accent' }: { size?: number; tone?: 'ink' | 'accent' }) { return <ActivityIndicator accessibilityLabel="Loading" size={size <= 20 ? 'small' : 'large'} color={tone === 'ink' ? colors.accentInk : colors.accent} />; }

const styles = StyleSheet.create({ alert: { minHeight: 48, borderRadius: radii.sm, padding: spacing[3], flexDirection: 'row', alignItems: 'center', gap: spacing[2] }, toast: { alignSelf: 'center', ...effects.shadow.raised }, alertText: { flex: 1, fontFamily: fontWeights.medium, fontSize: fontSizes.base }, scrim: { flex: 1, backgroundColor: effects.scrim.dialog, alignItems: 'center', justifyContent: 'center', padding: spacing[4] }, dialog: { width: '100%', maxHeight: '92%', backgroundColor: colors.surface.card, borderRadius: radii.md, borderWidth: 1, borderColor: colors.border.strong, padding: spacing[6] }, header: { flexDirection: 'row', alignItems: 'center', gap: spacing[3], marginBottom: spacing[4] }, grow: { flex: 1 }, title: { color: colors.text.primary, fontFamily: fontWeights.heavy, fontSize: fontSizes.xl }, subtitle: { color: colors.text.muted, fontFamily: fontWeights.regular, fontSize: fontSizes.base, marginTop: spacing[1] }, footer: { flexDirection: 'row', justifyContent: 'flex-end', gap: spacing[2], marginTop: spacing[4] }, sheetScrim: { flex: 1, justifyContent: 'flex-end', backgroundColor: effects.scrim.sheet }, sheet: { backgroundColor: colors.surface.card, borderTopLeftRadius: radii.lg, borderTopRightRadius: radii.lg, borderWidth: 1, borderColor: colors.border.strong, padding: spacing[5] }, handle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 2, backgroundColor: colors.border.strong, marginBottom: spacing[4] }, empty: { alignItems: 'center', gap: spacing[3] }, hex: { width: 56, height: 56, transform: [{ rotate: '45deg' }], borderRadius: radii.sm, backgroundColor: colors.accentWashStrong, alignItems: 'center', justifyContent: 'center' }, hexIcon: { transform: [{ rotate: '-45deg' }] }, emptyBody: { color: colors.text.muted, fontFamily: fontWeights.regular, fontSize: fontSizes.base, textAlign: 'center', lineHeight: 21 } });
