import { useRef, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import { colors, effects, fontSizes, fontWeights, radii, sizes, spacing } from '../tokens';
import { Icon } from '../icon/Icon';

type FieldFrameProps = { label?: React.ReactNode; hint?: React.ReactNode; error?: React.ReactNode; children: React.ReactNode };
function FieldFrame({ label, hint, error, children }: FieldFrameProps) { return <View style={styles.field}>{label ? <Text style={styles.label}>{label}</Text> : null}{children}{error ? <Text accessibilityRole="alert" accessibilityLiveRegion="polite" style={styles.error}>{error}</Text> : hint ? <Text style={styles.hint}>{hint}</Text> : null}</View>; }
export type InputProps = TextInputProps & { label?: React.ReactNode; hint?: React.ReactNode; error?: React.ReactNode; align?: 'left' | 'center' | 'right'; numeric?: boolean; suffix?: React.ReactNode };
export function Input({ label, hint, error, align = 'left', numeric, suffix, style, accessibilityLabel, ...props }: InputProps) { const name = accessibilityLabel ?? (typeof label === 'string' ? label : undefined); return <FieldFrame label={label} hint={hint} error={error}><View style={[styles.inputWrap, error ? styles.inputError : null]}><TextInput accessibilityLabel={name} placeholderTextColor={colors.text.faint} keyboardType={numeric ? 'decimal-pad' : props.keyboardType} {...props} style={[styles.input, numeric && styles.numeric, { textAlign: align }, style]} />{suffix ? <Text style={styles.suffix}>{suffix}</Text> : null}</View></FieldFrame>; }
export function Textarea({ rows = 3, ...props }: InputProps & { rows?: number }) { return <Input multiline numberOfLines={rows} textAlignVertical="top" {...props} style={[{ minHeight: rows * 24 + spacing[4] }, props.style]} />; }

type Option = string | { value: string; label: string };
export function Select({ label, options = [], placeholder = 'Select', value, onValueChange, disabled }: { label?: React.ReactNode; options?: Option[]; placeholder?: string; value?: string; onValueChange?: (value: string) => void; disabled?: boolean }) { const [open, setOpen] = useState(false); const normalized = options.map((option) => typeof option === 'string' ? { value: option, label: option } : option); const selected = normalized.find((option) => option.value === value); return <FieldFrame label={label}><Pressable accessibilityRole="button" accessibilityLabel={typeof label === 'string' ? label : 'Select'} accessibilityState={{ disabled, expanded: open }} disabled={disabled} onPress={() => setOpen(true)} style={({ pressed }) => [styles.inputWrap, { opacity: disabled ? 0.45 : pressed ? 0.75 : 1 }]}><Text style={[styles.selectText, !selected && styles.placeholder]}>{selected?.label ?? placeholder}</Text><Icon name="chevron-down" color={colors.text.muted} /></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><Pressable onPress={() => setOpen(false)} style={styles.scrim}><View style={styles.options}>{normalized.map((option) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: option.value === value }} key={option.value} onPress={() => { onValueChange?.(option.value); setOpen(false); }} style={styles.option}><Text style={styles.selectText}>{option.label}</Text>{option.value === value ? <Icon name="check" color={colors.accent} /> : null}</Pressable>)}</View></Pressable></Modal></FieldFrame>; }
export function Switch({ checked = false, onChange, label, description, disabled }: { checked?: boolean; onChange?: (next: boolean) => void; label?: React.ReactNode; description?: React.ReactNode; disabled?: boolean }) { const control = <Pressable accessibilityRole="switch" accessibilityLabel={typeof label === 'string' ? label : 'Toggle'} accessibilityState={{ checked, disabled }} disabled={disabled} onPress={() => onChange?.(!checked)} style={[styles.switchTrack, checked && styles.switchOn, disabled && styles.disabled]}><View style={[styles.switchThumb, checked && styles.thumbOn]} /></Pressable>; return label ? <View style={styles.switchRow}><View style={styles.switchCopy}><Text style={styles.label}>{label}</Text>{description ? <Text style={styles.hint}>{description}</Text> : null}</View>{control}</View> : control; }
export function CodeInput({ length = 6, value = '', onChange, onComplete, error, disabled, autoFocus }: { length?: number; value?: string; onChange?: (value: string) => void; onComplete?: (value: string) => void; error?: boolean; disabled?: boolean; autoFocus?: boolean }) { const ref = useRef<TextInput>(null); const change = (raw: string) => { const next = raw.replace(/\D/g, '').slice(0, length); onChange?.(next); if (next.length === length) onComplete?.(next); }; return <Pressable accessibilityRole="button" accessibilityLabel={`${length}-digit verification code`} onPress={() => ref.current?.focus()} style={styles.codeRow}><TextInput ref={ref} autoFocus={autoFocus} editable={!disabled} keyboardType="number-pad" textContentType="oneTimeCode" autoComplete="sms-otp" value={value} onChangeText={change} maxLength={length} style={styles.hiddenCode} /><View style={styles.codeBoxes}>{Array.from({ length }, (_, index) => <View key={index} style={[styles.codeBox, error && styles.inputError, index === value.length && !disabled && styles.codeActive]}><Text style={styles.codeText}>{value[index] ?? ''}</Text></View>)}</View></Pressable>; }

const styles = StyleSheet.create({ field: { gap: spacing[2] }, label: { color: colors.text.primary, fontFamily: fontWeights.semibold, fontSize: fontSizes.base }, hint: { color: colors.text.hint, fontFamily: fontWeights.regular, fontSize: fontSizes.sm }, error: { color: colors.status.errorInk, fontFamily: fontWeights.medium, fontSize: fontSizes.sm }, inputWrap: { minHeight: sizes.tapMin, borderWidth: 1, borderColor: colors.border.main, borderRadius: radii.xs, backgroundColor: colors.surface.sunken, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing[3] }, inputError: { borderColor: colors.status.error }, input: { flex: 1, color: colors.text.primary, fontFamily: fontWeights.regular, fontSize: fontSizes.lg, paddingVertical: spacing[3] }, numeric: { fontFamily: fontWeights.monoBold, fontSize: fontSizes.xxl }, suffix: { color: colors.text.muted, fontFamily: fontWeights.medium, marginLeft: spacing[2] }, selectText: { flex: 1, color: colors.text.primary, fontFamily: fontWeights.medium, fontSize: fontSizes.lg }, placeholder: { color: colors.text.hint }, scrim: { flex: 1, justifyContent: 'center', padding: spacing[6], backgroundColor: effects.scrim.dialog }, options: { borderRadius: radii.md, backgroundColor: colors.surface.card, padding: spacing[2], borderWidth: 1, borderColor: colors.border.strong }, option: { minHeight: sizes.tapMin, paddingHorizontal: spacing[3], flexDirection: 'row', alignItems: 'center' }, switchRow: { minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: spacing[4] }, switchCopy: { flex: 1 }, switchTrack: { width: 48, height: 28, borderRadius: 14, padding: 3, justifyContent: 'center', backgroundColor: colors.surface.active }, switchOn: { backgroundColor: colors.accent }, switchThumb: { width: 22, height: 22, borderRadius: 11, backgroundColor: colors.text.primary }, thumbOn: { alignSelf: 'flex-end', backgroundColor: colors.accentInk }, disabled: { opacity: 0.4 }, codeRow: { minHeight: 64 }, hiddenCode: { position: 'absolute', width: 1, height: 1, opacity: 0 }, codeBoxes: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing[2] }, codeBox: { flex: 1, maxWidth: 54, minWidth: 42, height: 58, borderRadius: radii.xs, borderWidth: 1, borderColor: colors.border.main, backgroundColor: colors.surface.sunken, alignItems: 'center', justifyContent: 'center' }, codeActive: { borderColor: colors.border.accentStrong }, codeText: { color: colors.text.primary, fontFamily: fontWeights.monoBold, fontSize: fontSizes.xxl } });
