import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, effects, fontSizes, fontWeights, radii, sizes, spacing } from '../tokens';
import { Icon } from '../icon/Icon';
import type { FitForgeIconName } from '../icon/icons';
import { Badge } from './core';

export type BottomNavItem = { value: string; label: string; icon: FitForgeIconName };
export function BottomNav({ items, value, onChange, center = { label: 'Start', icon: 'plus' } }: { items: BottomNavItem[]; value?: string; onChange?: (value: string) => void; center?: { label: string; icon?: FitForgeIconName; onClick?: () => void } }) { if (__DEV__ && items.length !== 4) throw new Error('BottomNav requires exactly four items'); const left = items.slice(0, 2); const right = items.slice(2); return <View style={styles.bottom}><View style={styles.navSide}>{left.map((item) => <NavItem key={item.value} item={item} selected={value === item.value} onPress={() => onChange?.(item.value)} />)}</View><Pressable accessibilityRole="button" accessibilityLabel={center.label} onPress={center.onClick} style={({ pressed }) => [styles.center, effects.shadow.raised, { opacity: pressed ? 0.76 : 1 }]}><Icon name={center.icon ?? 'plus'} color={colors.accentInk} size={28} /><Text style={styles.centerLabel}>{center.label}</Text></Pressable><View style={styles.navSide}>{right.map((item) => <NavItem key={item.value} item={item} selected={value === item.value} onPress={() => onChange?.(item.value)} />)}</View></View>; }
function NavItem({ item, selected, onPress }: { item: BottomNavItem; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="tab" accessibilityState={{ selected }} accessibilityLabel={item.label} onPress={onPress} style={styles.navItem}><Icon name={item.icon} color={selected ? colors.accent : colors.text.secondary} size={22} /><Text style={[styles.navLabel, selected && styles.navOn]}>{item.label}</Text></Pressable>; }
export type SidebarItem = BottomNavItem & { badge?: number };
export function Sidebar({ items, value, onChange, brand = 'FITFORGE', onSignOut }: { items: SidebarItem[]; value?: string; onChange?: (value: string) => void; brand?: string; onSignOut?: () => void }) { return <View style={styles.sidebar}><Text style={styles.brand}>{brand}</Text><View style={styles.sidebarList}>{items.map((item) => <Pressable key={item.value} accessibilityRole="tab" accessibilityState={{ selected: value === item.value }} onPress={() => onChange?.(item.value)} style={[styles.sidebarItem, value === item.value && styles.sidebarOn]}><Icon name={item.icon} color={value === item.value ? colors.accent : colors.text.muted} /><Text style={[styles.sidebarText, value === item.value && styles.navOn]}>{item.label}</Text>{item.badge ? <Badge count={item.badge} /> : null}</Pressable>)}</View>{onSignOut ? <Pressable accessibilityRole="button" accessibilityLabel="Sign out" onPress={onSignOut} style={styles.sidebarItem}><Icon name="log-out" color={colors.status.errorInk} /><Text style={[styles.sidebarText, { color: colors.status.errorInk }]}>Sign out</Text></Pressable> : null}</View>; }
export type TabItem = { id: string; label: React.ReactNode; icon?: FitForgeIconName };
export function Tabs({ tabs, value = tabs[0]?.id, onChange, variant = 'pill', iconOnly }: { tabs: TabItem[]; value?: string; onChange?: (id: string) => void; variant?: 'pill' | 'segmented' | 'underline' | 'stacked'; iconOnly?: boolean }) { return <View accessibilityRole="tablist" style={[styles.tabs, variant === 'segmented' && styles.segmented]}>{tabs.map((tab) => { const selected = tab.id === value; return <Pressable key={tab.id} accessibilityRole="tab" accessibilityState={{ selected }} accessibilityLabel={typeof tab.label === 'string' ? tab.label : tab.id} onPress={() => onChange?.(tab.id)} style={[styles.tab, variant === 'pill' && selected && styles.pillOn, variant === 'segmented' && selected && styles.segmentOn, variant === 'underline' && selected && styles.underlineOn, variant === 'stacked' && styles.stacked]}>{tab.icon ? <Icon name={tab.icon} color={selected ? colors.accent : colors.text.secondary} size={18} /> : null}{!iconOnly ? <Text style={[styles.tabText, selected && styles.navOn]}>{tab.label}</Text> : null}</Pressable>; })}</View>; }
const styles = StyleSheet.create({ bottom: { height: sizes.bottomNav, backgroundColor: colors.surface.nav, borderTopWidth: 1, borderColor: colors.border.main, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing[2], paddingBottom: spacing[1] }, navSide: { flex: 1, flexDirection: 'row' }, navItem: { flex: 1, minHeight: sizes.tapNav, alignItems: 'center', justifyContent: 'center', gap: 2 }, navLabel: { color: colors.text.secondary, fontFamily: fontWeights.medium, fontSize: fontSizes.xs }, navOn: { color: colors.accent }, center: { width: sizes.tapHex, height: sizes.tapHex, borderRadius: radii.lg, backgroundColor: colors.accent, transform: [{ translateY: -18 }, { rotate: '45deg' }], alignItems: 'center', justifyContent: 'center' }, centerLabel: { position: 'absolute', color: colors.accentInk, fontFamily: fontWeights.bold, fontSize: 9, transform: [{ rotate: '-45deg' }, { translateY: 24 }] }, sidebar: { width: 280, minHeight: '100%', backgroundColor: colors.surface.nav, padding: spacing[6], borderRightWidth: 1, borderColor: colors.border.main }, brand: { color: colors.accent, fontFamily: fontWeights.heavy, fontSize: fontSizes.h2, letterSpacing: -1 }, sidebarList: { flex: 1, gap: spacing[2], marginTop: spacing[8] }, sidebarItem: { minHeight: sizes.tapMin, borderRadius: radii.sm, paddingHorizontal: spacing[3], flexDirection: 'row', alignItems: 'center', gap: spacing[3] }, sidebarOn: { backgroundColor: colors.accentWash }, sidebarText: { flex: 1, color: colors.text.muted, fontFamily: fontWeights.semibold }, tabs: { flexDirection: 'row', gap: spacing[1] }, segmented: { padding: spacing[1], borderRadius: radii.pill, backgroundColor: colors.surface.quiet }, tab: { flex: 1, minHeight: sizes.tapMin, paddingHorizontal: spacing[3], flexDirection: 'row', gap: spacing[2], alignItems: 'center', justifyContent: 'center', borderRadius: radii.pill, borderBottomWidth: 2, borderBottomColor: 'transparent' }, tabText: { color: colors.text.secondary, fontFamily: fontWeights.semibold, fontSize: fontSizes.sm }, pillOn: { backgroundColor: colors.accentWashStrong }, segmentOn: { backgroundColor: colors.surface.active }, underlineOn: { borderBottomColor: colors.accent, borderRadius: 0 }, stacked: { flexDirection: 'column' } });
