import { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, fontSizes, fontWeights, radii, sizes, spacing } from '../tokens';
import { Icon } from '../icon/Icon';
import { Button, Card, Chip, IconButton } from './core';
import { Input } from './forms';
import { ProgressBar } from './data';

export function SetRow({ index, weight, reps, unit = 'kg', completed, onWeightChange, onRepsChange, onComplete, onRemove }: { index: number; weight: number | string; reps: number | string; unit?: 'kg' | 'lbs'; completed?: boolean; onWeightChange?: (value: string) => void; onRepsChange?: (value: string) => void; onComplete?: () => void; onRemove?: () => void }) { return <View style={[styles.setRow, completed && styles.setDone]}><Text style={styles.setIndex}>{index}</Text><View style={styles.field}><Input accessibilityLabel={`Set ${index} weight`} numeric align="center" suffix={unit} value={String(weight)} editable={!completed} onChangeText={onWeightChange} /></View><View style={styles.field}><Input accessibilityLabel={`Set ${index} reps`} numeric align="center" value={String(reps)} editable={!completed} onChangeText={onRepsChange} /></View><Pressable accessibilityRole="checkbox" accessibilityLabel={`Complete set ${index}`} accessibilityState={{ checked: completed }} onPress={onComplete} style={[styles.complete, completed && styles.completeOn]}><Icon name="check" size={18} color={completed ? colors.accentInk : colors.text.muted} /></Pressable>{onRemove ? <IconButton icon="trash" label={`Remove set ${index}`} size="sm" onPress={onRemove} /> : null}</View>; }
export function RestTimer({ duration = 90, variant = 'bar', autoDismiss = 0, onSkip, onDismiss, now = Date.now }: { duration?: number; variant?: 'bar' | 'card'; autoDismiss?: number; onSkip?: () => void; onDismiss?: () => void; now?: () => number }) { const endAt = useMemo(() => now() + duration * 1000, [duration, now]); const [remaining, setRemaining] = useState(duration); useEffect(() => { const update = () => setRemaining(Math.max(0, Math.ceil((endAt - now()) / 1000))); update(); const id = setInterval(update, 250); return () => clearInterval(id); }, [endAt, now]); useEffect(() => { if (remaining === 0 && autoDismiss > 0) { const id = setTimeout(() => onDismiss?.(), autoDismiss); return () => clearTimeout(id); } }, [remaining, autoDismiss, onDismiss]); const display = `${String(Math.floor(remaining / 60)).padStart(2, '0')}:${String(remaining % 60).padStart(2, '0')}`; return <Card tone="accent" padding={variant === 'bar' ? 'sm' : 'md'} accessibilityLabel={`Rest timer ${display}`}><View style={styles.timerRow}><View style={styles.timerCopy}><Text style={styles.timerLabel}>{remaining > 0 ? 'REST' : 'REST COMPLETE'}</Text><Text style={styles.timer}>{display}</Text></View>{onSkip && remaining > 0 ? <Button variant="ghost" onPress={onSkip}>Skip</Button> : onDismiss ? <Button variant="ghost" onPress={onDismiss}>Dismiss</Button> : null}</View><ProgressBar value={duration - remaining} max={duration} /></Card>; }
export function AISuggestionCard({ icon = 'brain', title, description, priority = 'medium', confidence, action }: { icon?: string; title: React.ReactNode; description: React.ReactNode; priority?: 'high' | 'medium' | 'low'; confidence?: number; action?: React.ReactNode }) { const safeConfidence = Math.round(Math.min(Math.max(confidence ?? 0, 0), 1) * 100); return <Card padding="sm"><View style={styles.aiHeader}><Icon name={icon} color={colors.accent} /><Text style={styles.aiTitle}>{title}</Text><Chip label={priority.toUpperCase()} tone={priority} /></View><Text style={styles.description}>{description}</Text>{confidence !== undefined ? <Text accessibilityLabel={`${safeConfidence}% confidence`} style={styles.confidence}>{safeConfidence}% confidence</Text> : null}{action ? <View style={styles.action}>{action}</View> : null}</Card>; }
const styles = StyleSheet.create({ setRow: { minHeight: 72, borderRadius: radii.sm, backgroundColor: colors.surface.quiet, borderWidth: 1, borderColor: colors.border.main, padding: spacing[2], flexDirection: 'row', alignItems: 'center', gap: spacing[2] }, setDone: { borderColor: colors.border.accent, backgroundColor: colors.accentWash }, setIndex: { width: 24, color: colors.text.muted, fontFamily: fontWeights.monoBold, textAlign: 'center' }, field: { flex: 1 }, complete: { width: sizes.tapMin, height: sizes.tapMin, borderRadius: 22, borderWidth: 1, borderColor: colors.border.strong, alignItems: 'center', justifyContent: 'center' }, completeOn: { backgroundColor: colors.accent, borderColor: colors.accent }, timerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing[3] }, timerCopy: { flex: 1 }, timerLabel: { color: colors.accent, fontFamily: fontWeights.bold, fontSize: fontSizes.xs, letterSpacing: 1.2 }, timer: { color: colors.text.primary, fontFamily: fontWeights.monoBold, fontSize: fontSizes.h2 }, aiHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] }, aiTitle: { flex: 1, color: colors.text.primary, fontFamily: fontWeights.bold, fontSize: fontSizes.lg }, description: { color: colors.text.muted, fontFamily: fontWeights.regular, fontSize: fontSizes.base, lineHeight: 21, marginTop: spacing[3] }, confidence: { color: colors.text.secondary, fontFamily: fontWeights.mono, fontSize: fontSizes.xs, marginTop: spacing[2] }, action: { marginTop: spacing[3] } });
