import { useState, type ReactNode } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { AddRow, AISuggestionCard, Alert, Badge, BottomNav, Button, Card, Chip, CodeInput, Dialog, EmptyState, Heatmap, Icon, IconButton, Input, ProgressBar, ProgressRing, RestTimer, Select, SelectableRow, Sheet, Sidebar, Skeleton, Spinner, StatCard, Switch, Tabs, Textarea, SetRow, colors, fontSizes, fontWeights, spacing } from '@/design-system';
import { Screen } from '@/features/app-shell/Screen';

const navItems = [{ value: 'home', label: 'Home', icon: 'home' }, { value: 'workouts', label: 'Workouts', icon: 'dumbbell' }, { value: 'history', label: 'History', icon: 'history' }, { value: 'progress', label: 'Progress', icon: 'line-chart' }] as const;
function Section({ title, children }: { title: string; children: ReactNode }) { return <View style={styles.section}><Text accessibilityRole="header" style={styles.heading}>{title}</Text><View style={styles.stack}>{children}</View></View>; }

export default function GalleryRoute() {
  const [selected, setSelected] = useState('strength'); const [enabled, setEnabled] = useState(true); const [code, setCode] = useState(''); const [choice, setChoice] = useState('Metric'); const [tab, setTab] = useState('overview'); const [dialog, setDialog] = useState(false); const [sheet, setSheet] = useState(false); const [nav, setNav] = useState('home');
  return <Screen eyebrow="DEVELOPMENT ONLY" title="Native component gallery">
    <Section title="Core · Default / Selected / Disabled / Loading">
      <View style={styles.row}><Button icon="plus">Primary</Button><Button variant="outline">Outline</Button></View><Button disabled>Disabled</Button><Button loading>Loading</Button><View style={styles.row}><Icon name="dumbbell" color={colors.accent} /><IconButton icon="info" label="Information" /><Badge count={3} /><Badge dot /><Chip label="CUSTOM" tone="accent" /></View><Card><Text style={styles.body}>Default Card</Text></Card><SelectableRow title="Strength" sub="Build power and muscle" selected={selected === 'strength'} onPress={() => setSelected('strength')} /><AddRow label="Add a day" /><StatCard icon="flame" value="12,840" meta="kg" label="Volume" />
    </Section>
    <Section title="Data"><ProgressBar value={3} max={5} label="Weekly goal" valueLabel="3 / 5" /><View style={styles.row}><ProgressRing current={3} target={4} label="Workouts" /><ProgressRing current={42} target={60} colorStart={colors.data.warm} label="Sets" /></View><Heatmap year={2026} totalWorkouts={12} workoutDays={9} values={Array.from({ length: 35 }, (_, index) => index % 4 === 0 ? 1 : 0)} /></Section>
    <Section title="Feedback · Error / Empty / Dialog / Sheet"><Alert tone="error">Unable to load the latest data.</Alert><Alert tone="info">Offline data is still available.</Alert><EmptyState title="No workouts yet" body="Start a session to build your history." action={<Button>Start workout</Button>} /><View style={styles.row}><Button variant="secondary" onPress={() => setDialog(true)}>Dialog</Button><Button variant="secondary" onPress={() => setSheet(true)}>Sheet</Button></View><View style={styles.row}><Skeleton variant="circle" width={44} height={44} /><View style={styles.grow}><Skeleton variant="text" height={14} /><Skeleton variant="text" width="70%" height={12} /></View><Spinner /></View></Section>
    <Section title="Forms · Error / Disabled"><Input label="Exercise" value="Bench press" /><Input label="Weight" numeric suffix="kg" value="80" /><Input label="Invalid value" error="Enter a valid number" value="" /><Textarea label="Notes" hint="Private workout note" value="Controlled tempo" /><Select label="Units" value={choice} options={['Metric', 'Imperial']} onValueChange={setChoice} /><Switch label="Rest notifications" description="Alert when rest ends" checked={enabled} onChange={setEnabled} /><Switch label="Disabled setting" disabled /><CodeInput value={code} onChange={setCode} /></Section>
    <Section title="Navigation"><Tabs tabs={[{ id: 'overview', label: 'Overview', icon: 'dumbbell' }, { id: 'history', label: 'History', icon: 'history' }]} value={tab} onChange={setTab} /><Sidebar brand="FITFORGE" items={[...navItems]} value={nav} onChange={setNav} onSignOut={() => undefined} /><BottomNav items={[...navItems]} value={nav} onChange={setNav} /></Section>
    <Section title="Workout"><SetRow index={1} weight="80" reps="8" /><SetRow index={2} weight="82.5" reps="8" completed /><RestTimer duration={90} onSkip={() => undefined} /><AISuggestionCard title="Increase weight" description="Your recent sets support a small load increase." priority="high" confidence={0.84} action={<Button variant="outline">Apply</Button>} /></Section>
    <Dialog open={dialog} title="Finish workout?" subtitle="Your completed sets are ready." onClose={() => setDialog(false)} footer={<Button onPress={() => setDialog(false)}>Finish</Button>}><Text style={styles.body}>Review the session before saving.</Text></Dialog>
    <Sheet open={sheet} title="Leave workout" onClose={() => setSheet(false)}><Button fullWidth>Save as incomplete</Button><Button fullWidth variant="danger">Discard workout</Button></Sheet>
  </Screen>;
}
const styles = StyleSheet.create({ section: { marginBottom: spacing[10] }, heading: { color: colors.text.primary, fontFamily: fontWeights.heavy, fontSize: fontSizes.xl, marginBottom: spacing[4] }, stack: { gap: spacing[3] }, row: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: spacing[3] }, grow: { flex: 1, gap: spacing[2] }, body: { color: colors.text.muted, fontFamily: fontWeights.regular, fontSize: fontSizes.base } });
